apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: raycluster
spec:
  rayVersion: "2.55.1"

  headGroupSpec:
    serviceType: LoadBalancer

    rayStartParams:
      dashboard-host: "0.0.0.0"
      num-cpus: "0"

    template:
      spec:
        hostAliases:
          - ip: 192.168.0.180
            hostnames:
              - mlflow.cnapcloud.com

        volumes:
          - name: ray-data-storage
            persistentVolumeClaim:
              claimName: ray-data-pvc

        containers:
          - name: ray-head
            image: cnapcloud/ray-llm:2.55.1-py312-cpu-aarch64
            imagePullPolicy: Always

            resources:
              requests:
                cpu: 200m
                memory: 4Gi
              limits:
                cpu: "2"
                memory: 4Gi

            volumeMounts:
              - name: ray-data-storage
                mountPath: /mnt/data

            ports:
              - containerPort: 6379
                name: gcs

              - containerPort: 8265
                name: dashboard

              - containerPort: 10001
                name: client

              - containerPort: 8000
                name: serve

              - containerPort: 8080
                name: metrics

  workerGroupSpecs:
    - replicas: 1
      minReplicas: 1
      maxReplicas: 3
      groupName: worker-group

      rayStartParams: {}

      template:
        metadata:
          labels:
            ray.io/group: worker-group

        spec:
          hostAliases:
            - ip: 192.168.0.180
              hostnames:
                - mlflow.cnapcloud.com

          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: ray.io/group
                          operator: In
                          values:
                            - worker-group
                    topologyKey: kubernetes.io/hostname

          volumes:
            - name: ray-data-storage
              persistentVolumeClaim:
                claimName: ray-data-pvc

          containers:
            - name: ray-worker
              image: cnapcloud/ray-llm:2.55.1-py312-cpu-aarch64
              imagePullPolicy: Always

              resources:
                requests:
                  cpu: "4"
                  memory: 10Gi
                limits:
                  cpu: "4"
                  memory: 10Gi

              volumeMounts:
                - name: ray-data-storage
                  mountPath: /mnt/data

              readinessProbe:
                exec:
                  command:
                    - bash
                    - -c
                    - >
                      wget --tries 1 -T 2 -q -O-
                      http://localhost:52365/api/local_raylet_healthz
                      | grep success

                initialDelaySeconds: 30
                periodSeconds: 5
                failureThreshold: 5
                timeoutSeconds: 3