apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/airflow-rayjob-rbac.yaml
  - resources/servicemonitor.yaml

configMapGenerator:
  - name: grafana-dashboards-airflow
    files:
      - grafana-dashboards/airflow-dashboard.json
    options:
      labels:
        grafana_dashboard: "1"

secretGenerator:
  - name: airflow-api-secret-key
    files:
      - api-secret-key=resources/.generated/airflow-api-secret-key
    type: Opaque
  - name: airflow-jwt-secret
    files:
      - jwt-secret=resources/.generated/airflow-jwt-secret
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true