apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/airflow-rayjob-rbac.yaml

secretGenerator:
  - name: airflow-api-secret-key
    files:
      - api-secret-key=resources/.generated/airflow-api-secret-key
    type: Opaque
  - name: airflow-jwt-secret
    files:
      - jwt-secret=resources/.generated/airflow-jwt-secret
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true