apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: grafana
name: grafana
chartHome: ../../base/helm
chart: grafana
releaseName: grafana
valuesFile: ./helm/values-dev.yaml
includeCRDs: true
namespace: mlops