## [KubeRay] 이미 생성되어 운영 중인 RayCluster에 분산 작업을 제출하는 RayJob 설정입니다.
## 
## 동작 메커니즘:
## 1. Submitter(Job 주체)가 지정된 RayCluster의 Head Node(Head Pod)로 entrypoint 파이썬 코드를 전송합니다.
## 2. Head Node는 수신된 작업을 스케줄링하여 클러스터 내의 Worker Node(Worker Pod)들에게 분산 배포합니다.
## 3. Worker Node들이 병렬로 태스크를 실행하고, 그 결과를 다시 취합하여 출력합니다.

apiVersion: ray.io/v1
kind: RayJob
metadata:
  generateName: example-rayjob-subnmitter-
spec:
  clusterSelector:
    ray.io/cluster: raycluster

  # 제출할 Python 코드
  entrypoint: |
    python -c "
    import ray, socket, time
    ray.init(address='auto')

    @ray.remote
    def worker_task(i):
        return f'Task {i} executed on {socket.gethostname()}'

    results = ray.get([worker_task.remote(i) for i in range(5)])

    print('=== RESULTS ===')
    for result in results:
        print(result)

    raise Exception('Intentional exception at the end of the job')
    "

  # Job 완료 후 자동 정리 여부
  shutdownAfterJobFinishes: true

  # submitter pod 설정
  submitterPodTemplate:
    spec:
      restartPolicy: Never
      containers:
        - name: ray-job-submitter
          image: rayproject/ray:2.55.1-py312-cpu-aarch64
          imagePullPolicy: Always
