apiVersion: ray.io/v1
kind: RayService
metadata:
  name: llm-service
spec:
  # Ray Serve 배포 설정
  serveConfigV2: |
    applications:
      - name: llm_app
        import_path: serve_app:deployment
        route_prefix: /
        deployments:
          - name: LLMService
            num_replicas: 2
            ray_actor_options:
              num_cpus: 1

  # Ray 클러스터 구조 설정
  rayClusterConfig:
    rayVersion: '2.55.1'
    headGroupSpec:
      rayStartParams:
        dashboard-host: '0.0.0.0'
        num-cpus: '0'
      template:
        spec:
          containers:
            - name: ray-head
              image: cnapcloud/ray-ollama-service:latest
              imagePullPolicy: Always
              ports:
              - containerPort: 6379
                name: gcs
              - containerPort: 8265
                name: dashboard
              - containerPort: 8000
                name: serve
              - containerPort: 8080
                name: metrics
    workerGroupSpecs:
      - replicas: 2
        minReplicas: 1
        maxReplicas: 3
        groupName: worker-group
        rayStartParams: {}
        template:
          spec:
            containers:
              - name: ray-worker
                image: cnapcloud/ray-ollama-service:latest
                imagePullPolicy: Always
                resources:
                  limits:
                    cpu: "1"
                  requests:
                    cpu: 100m
                readinessProbe:
                  exec:
                    command:
                      - bash
                      - -c
                      - wget --tries 1 -T 2 -q -O- http://localhost:52365/api/local_raylet_healthz | grep success
                  initialDelaySeconds: 30
                  periodSeconds: 5
                  failureThreshold: 5
                  timeoutSeconds: 3