# 1. Ingress 설정 (Nginx Ingress Controller 사용 가정)
ingress:
  enabled: true
  apiServer:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - name: "airflow.cnapcloud.com"
        tls:
          enabled: true
          secretName: "airflow-tls"

# 2. 내부 PostgreSQL DB 설정 (Bitnami 서브차트)
postgresql:
  enabled: true
  auth:
    database: "airflow"
    username: "airflow"
    password: "password"
    postgresPassword: "password" # root 패스워드
  primary:
    persistence:
      enabled: true
      storageClass: "nfs" 
      accessModes:
        - ReadWriteOnce
      size: "2Gi"

# 3. 에어플로우 컴포넌트들이 내부 DB에 접속하기 위한 연결 정보 매핑
data:
  metadataConnection:
    protocol: postgresql
    user: "airflow"
    pass: "password"
    db: "airflow"

# 4. 최초 설치 시 DB 초기화 및 관리자 생성을 위한 Job 설정
createUserJob:
  enabled: true
  defaultUser:
    role: Admin
    username: admin
    email: admin@cnapcloud.com
    firstName: admin
    lastName: system
    password: password
  useHelmHooks: true
  applyCustomEnv: true

migrateDatabaseJob:
  enabled: true
  useHelmHooks: true
  applyCustomEnv: true
  
# argocd를 사용하는 경우 
# migrateDatabaseJob:
#  jobAnnotations:
#    "argocd.argoproj.io/hook": Sync

# 5. github workflow 동기화 설정  
dags:
  gitSync:
    enabled: true
    repo: "https://github.com/cnapcloud/mlops.git"
    branch: "main"
    subPath: "platform/airflow/dags"
    wait: 20
    credentialsSecret: ""
    sshKeySecret: ""

# 6. 추가적으로 필요한 Python 패키지 설치를 위한 환경 변수 설정
env:
  - name: _PIP_ADDITIONAL_DEPENDENCIES
    value: "kubernetes>=29.0.0 kubernetes-asyncio==29.0.0 apache-airflow-providers-cncf-kubernetes==10.17.0"

workers:
  replicas: 1
  persistence:
    enabled: true
    size: 2Gi

triggerer:
  env:
    - name: PYTHONPATH
      value: "/opt/airflow/dags/repo/airflow/dags"
  replicas: 1
  persistence:
    enabled: true
    size: 2Gi

apiSecretKeySecretName: airflow-api-secret-key   # AIRFLOW__API__SECRET_KEY
jwtSecretName: airflow-jwt-secret                # AIRFLOW__API_AUTH__JWT_SECRET


# 다른 네임스페이스에 Pod를 띄울 수 있는 권한 설정
multiNamespaceMode: true