apiVersion: ray.io/v1
kind: RayJob
metadata:
  generateName: example-archive-rayjob-
spec:
  clusterSelector:
    ray.io/cluster: raycluster
  entrypoint: >
    bash -c "cd taxi-xgboost && python step3_train.py"
  runtimeEnvYAML: |
    working_dir: "https://github.com/cnapcloud/mlops/archive/refs/heads/main.zip"
    pip:
      - ray
      - pandas
      - xgboost==3.2.0
      - mlflow
      - scikit-learn

  shutdownAfterJobFinishes: true
  submitterPodTemplate:
    spec:
      restartPolicy: Never
      containers:
        - name: ray-job-submitter
          image: rayproject/ray:2.55.1-py312-cpu-aarch64
          imagePullPolicy: Always