apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: raycluster
spec:
  rayVersion: "2.55.1"

  enableInTreeAutoscaling: true

  autoscalerOptions:
    upscalingMode: Default
    # `idleTimeoutSeconds` is the number of seconds to wait before scaling down a worker pod which is not using Ray resources.
    idleTimeoutSeconds: 60
    imagePullPolicy: IfNotPresent
    securityContext: {}
    env:
      - name: AUTOSCALER_UPDATE_INTERVAL_S
        value: "5"
      - name: RAY_LOGGER_LEVEL
        value: "info"
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "500m"
        memory: "512Mi"

  headGroupSpec:
    serviceType: LoadBalancer

    rayStartParams:
      dashboard-host: "0.0.0.0"
      num-cpus: "0"

    template:
      spec:
        hostAliases:
          - ip: 192.168.0.180
            hostnames:
              - mlflow.cnapcloud.com

        volumes:
          - name: ray-data-storage
            persistentVolumeClaim:
              claimName: ray-data-pvc

        containers:
          - name: ray-head
            image: cnapcloud/ray-llm:2.55.1-py312-cpu-aarch64
            imagePullPolicy: Always

            resources:
              requests:
                cpu: 200m
                memory: 4Gi
              limits:
                cpu: "2"
                memory: 4Gi

            env:
              - name: TZ
                value: Asia/Seoul            
              - name: RAY_GRAFANA_IFRAME_HOST
                value: http://grafana.cnapcloud.com
              - name: RAY_GRAFANA_HOST
                value: http://grafana.mlops.svc:80
              - name: RAY_PROMETHEUS_HOST
                value: http://prometheus-kube-prometheus-prometheus.mlops.svc:9090

            volumeMounts:
              - name: ray-data-storage
                mountPath: /mnt/data

            ports:
              - containerPort: 6379
                name: gcs
              - containerPort: 8265
                name: dashboard
              - containerPort: 10001
                name: client
              - containerPort: 8000
                name: serve
              - containerPort: 8080
                name: metrics
              - containerPort: 44217
                name: as-metrics
                protocol: TCP
              - containerPort: 44227
                name: dash-metrics
                protocol: TCP                

  workerGroupSpecs:
    - replicas: 0
      minReplicas: 0
      maxReplicas: 2
      groupName: worker-group

      rayStartParams:
        object-store-memory: "5g"

      template:
        metadata:
          labels:
            ray.io/group: worker-group

        spec:
          hostAliases:
            - ip: 192.168.0.180
              hostnames:
                - mlflow.cnapcloud.com

          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: ray.io/group
                          operator: In
                          values:
                            - worker-group
                    topologyKey: kubernetes.io/hostname

          volumes:
            - name: ray-data-storage
              persistentVolumeClaim:
                claimName: ray-data-pvc

          containers:
            - name: ray-worker
              image: cnapcloud/ray-llm:2.55.1-py312-cpu-aarch64
              imagePullPolicy: Always
              env:
                - name: TZ
                  value: Asia/Seoul   

              resources:
                requests:
                  cpu: "4"
                  memory: 10Gi
                limits:
                  cpu: "4"
                  memory: 10Gi

              volumeMounts:
                - name: ray-data-storage
                  mountPath: /mnt/data

              readinessProbe:
                exec:
                  command:
                    - bash
                    - -c
                    - >
                      wget --tries 1 -T 2 -q -O-
                      http://localhost:52365/api/local_raylet_healthz
                      | grep success

                initialDelaySeconds: 30
                periodSeconds: 5
                failureThreshold: 5
                timeoutSeconds: 3